services:
  kanban.server:
    image: explazy/kanbanserver
    build:
      context: .
      dockerfile: Kanban.Server/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgresql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=kanban

  postgresql:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: kanban
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  postgres_data: