//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanban.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kanban.Server.Resources.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя и пароль пользователя при авторизации не могут быть null..
        /// </summary>
        public static string AuthUserDataIsNull {
            get {
                return ResourceManager.GetString("AuthUserDataIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объект для создания доски не может быть null..
        /// </summary>
        public static string BoardCreateModelIsNull {
            get {
                return ResourceManager.GetString("BoardCreateModelIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор доски не может быть меньше или равен нулю..
        /// </summary>
        public static string BoardIdLessOrEqualZero {
            get {
                return ResourceManager.GetString("BoardIdLessOrEqualZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доска по указанному идентификатору не найдена..
        /// </summary>
        public static string BoardIsNull {
            get {
                return ResourceManager.GetString("BoardIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя доски не может быть пустым или null..
        /// </summary>
        public static string BoardNameIsNullOrEmpty {
            get {
                return ResourceManager.GetString("BoardNameIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объект для изменения доски не может быть null..
        /// </summary>
        public static string BoardUpdateModelIsNull {
            get {
                return ResourceManager.GetString("BoardUpdateModelIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объект для создания колонки не может быть null..
        /// </summary>
        public static string ColumnCreateModelIsNull {
            get {
                return ResourceManager.GetString("ColumnCreateModelIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор колонки не может быть меньше или равен нулю..
        /// </summary>
        public static string ColumnIdLessOrEqualZero {
            get {
                return ResourceManager.GetString("ColumnIdLessOrEqualZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя колонки не может быть пустым или null..
        /// </summary>
        public static string ColumnNameIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ColumnNameIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Позиция колонки не может быть меньше нуля..
        /// </summary>
        public static string ColumnPositionLessThanZero {
            get {
                return ResourceManager.GetString("ColumnPositionLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объект для изменения колонки не может быть null..
        /// </summary>
        public static string ColumnUpdateModelIsNull {
            get {
                return ResourceManager.GetString("ColumnUpdateModelIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email не соответствует формату email-адреса..
        /// </summary>
        public static string EmailRegexDoNotMatch {
            get {
                return ResourceManager.GetString("EmailRegexDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль должен быть длиной от 6 символов и включать хотя бы одну букву и одну цифру..
        /// </summary>
        public static string PasswordRegexDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordRegexDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароли не совпадают..
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные пользователя при регистрации не могут быть null..
        /// </summary>
        public static string RegisterUserDataIsNull {
            get {
                return ResourceManager.GetString("RegisterUserDataIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор пользователя не может быть меньше или равен нулю..
        /// </summary>
        public static string UserIdLessOrEqualZero {
            get {
                return ResourceManager.GetString("UserIdLessOrEqualZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя пользователя должно состоять не менее, чем из 4-х латинских букв..
        /// </summary>
        public static string UsernameRegexDoNotMatch {
            get {
                return ResourceManager.GetString("UsernameRegexDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь с указанным email уже существует..
        /// </summary>
        public static string UserWithSpecifiedEmailAlreadyExist {
            get {
                return ResourceManager.GetString("UserWithSpecifiedEmailAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь с указанным именем уже существует..
        /// </summary>
        public static string UserWithSpecifiedNameAlreadyExist {
            get {
                return ResourceManager.GetString("UserWithSpecifiedNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователя с таким именем не существует..
        /// </summary>
        public static string UserWithSpecifiedNameDoesNotExist {
            get {
                return ResourceManager.GetString("UserWithSpecifiedNameDoesNotExist", resourceCulture);
            }
        }
    }
}
